version: "3.8"
services: 

    emane-service-1:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            - a_ota
        container_name: emane-service1
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        environment:
            - NODE_NO=1
        tty: true
        stdin_open: true
        privileged: true
        entrypoint: /bin/bash

    emane-service-2:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            - a_ota
        container_name: emane-service2
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        environment:
            - NODE_NO=2
        tty: true
        stdin_open: true
        privileged: true
        entrypoint: /bin/bash

    helper-service:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            - a_ota
        container_name: helper-service
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        tty: true
        stdin_open: true
        privileged: true
        entrypoint: /bin/bash

networks:
    a_ota:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24