version: "3.8"
services: 

    emane-service-1:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            a_ota:
                ipv4_address: 10.100.0.2
        container_name: emane-service1
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        tty: true
        stdin_open: true
        privileged: true
        entrypoint: /bin/bash

    emane-service-2:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            a_ota:
                ipv4_address: 10.100.0.3
        container_name: emane-service2
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        tty: true
        stdin_open: true
        privileged: true
        entrypoint: /bin/bash

networks:
    a_ota:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24