version: "3.8"
services: 

    emane-service-1:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            a_ota:
                ipv4_address: 10.101.0.2
        container_name: emane-service1
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        environment:
            - NODE_NO=1
        tty: true
        stdin_open: true
        privileged: true
        entrypoint:  /bin/sh

    emane-service-2:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            a_ota:
                ipv4_address: 10.101.0.3
        container_name: emane-service2
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        environment:
            - NODE_NO=2
        tty: true
        stdin_open: true
        privileged: true
        entrypoint:  /bin/sh

    emane-service-3:
        #image: ubuntu:18.04
        build:
            context: ../
            dockerfile: dockerfiles/emane-environment
        networks:
            a_ota:
                ipv4_address: 10.101.0.4
        container_name: emane-service3
        volumes:
            - /home/user2/work/idf/emane/emane-tutorial/:/emane-tutorial
        environment:
            - NODE_NO=3
        tty: true
        stdin_open: true
        privileged: true
        entrypoint:  /bin/sh


networks:
    a_ota:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.101.0.0/24